### PR TITLE
replace HTML::Tidy with HTML::Tidy5

### PR DESCRIPTION
**Pull request by gugod**
This PR replaces the use of `HTML::Tidy` with `HTML::Tidy5`.

As described in issue #20 , this helps on the installation.

### CODE REVIEW

**Comment by davorg** [comment]
Thanks. That's a good idea. But it seems that this fix isn't passing tests (because HTML::Tidy5 isn't installing correctly on the GitHub Actions container).

**Comment by davorg** [comment]
I have a feeling that I might have investigated this before. But I got scared when I found that HTML::Tidy5 hadn't been updated since 2019 and had a [huge number of test failures](http://matrix.cpantesters.org/?dist=HTML-Tidy5+1.06).

**Comment by gugod** [comment]
於 2023年5月8日 下午6:39:28 [GMT+09:00]，Dave Cross ***@***.***> 寫到：
>I have a feeling that I might have investigated this before. But I got scared when I found that HTML::Tidy5 hadn't been updated since 2019 and had a [huge number of test failures](http://matrix.cpantesters.org/?dist=HTML-Tidy5+1.06).
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/davorg/perlanet/pull/21#issuecomment-1538065088
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
thanks for the insight. I could spend some time looking into it. 
--
Kang-min Liu

**Comment by davorg** [comment]
That would be great, thanks.

I'd love to get a more modern HTML Tidying tool into Perlanet, but I don't want to replace one obsolete tool with another slightly-less-obsolete one :-)

**Comment by gugod** [comment]
The failure of CI can be repaired by also replacing `Alien::Tidyp` with a ubuntu packgae named `libtidy-dev`. I tried `apt install -y libtidy-dev && cpanm -L ~/local HTML::Tidy5` and that works.... sort of.  The compilation finished but there is one test failure at `opt-00.t` . It seems to me a minor issues caused , which is already  addressed in this PR: https://github.com/petdance/html-tidy5/pull/14/files#diff-fd89b5417ae246ab3879df64898e063978830ccce6a88f969eee7b1f9f65e5ae

**Comment by davorg** [comment]
> The failure of CI can be repaired by also replacing `Alien::Tidyp` with a ubuntu package named `libtidy-dev`.

But that's only going to work on Ubuntu. I realise I'm currently only testing on Ubuntu, but there should be no reason why this isn't tested on Windows and MacOS too. I'm going to investigate changing `Alien::Tidyp` with `Alien::TidyHTML5` which should work on all platforms.

> It seems to me a minor issues caused , which is already addressed in this PR: https://github.com/petdance/html-tidy5/pull/14/files#diff-fd89b5417ae246ab3879df64898e063978830ccce6a88f969eee7b1f9f65e5ae

That's a good demonstration of why I'm worried about this change. That PR is from almost two years ago and still hasn't been merged, let alone released.

I'm very worried about releasing software that's dependent on defunct modules.

**Comment by davorg** [comment]
(Also, it looks like you didn't change the Coverage tests to install the new library)

**Comment by davorg** [comment]
I found `Alien::HTMLTidy5` and `HTML::T5` which both seem to be better maintained.

Perlanet 3.0.1 is on the wat to CPAN now.

**Pull request closed without merging**
